# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

clone_depth: 1

environment:
  matrix:
    - nodejs_version: "8.9"

platform:
  - x64

cache:
 - "%LOCALAPPDATA%\\Yarn"

branches:
  only:
    - master

# Install scripts. (runs after repo cloning)
install:
  # Let's try to get things working
  # Install Node 4 ---------------------------------------------------------
  - ps: Install-Product node 8.11
  # Installation, deps -----------------------------------------------------
  - yarn install --no-progress --no-emojis
  - npm link # yarn link doesn't seem to work

test_script:
  - md C:\clitest
  - cd C:\clitest
  - ghost install local

on_failure:
  - ps: Get-ChildItem C:\Users\appveyor\.ghost\logs\*.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

# Set build version format here instead of in the admin panel.
build: off
version: "{build}"
